name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        # (Optional) Add any pytest or lint commands
        echo "No tests defined."

  build_and_push:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
    - name: Log in to Google Container Registry
      uses: docker/login-action@v2
      with:
        registry: gcr.io
        username: oauth2accesstoken
        password: ${{ secrets.GCP_GAR_TOKEN }}
    - name: Build and push Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/voice-ai-agent:latest .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/voice-ai-agent:latest

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
    - name: SSH Deploy to GCE VM
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.VM_IP }}
        username: my-user
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          docker pull gcr.io/${{ secrets.GCP_PROJECT_ID }}/voice-ai-agent:latest
          docker stop voice_agent || true
          docker rm voice_agent || true
          docker run -d --name voice_agent -p 8000:8000 \
            -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
            -e TWILIO_ACCOUNT_SID=${{ secrets.TWILIO_ACCOUNT_SID }} \
            -e TWILIO_AUTH_TOKEN=${{ secrets.TWILIO_AUTH_TOKEN }} \
            gcr.io/${{ secrets.GCP_PROJECT_ID }}/voice-ai-agent:latest
